---
- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  ## Define the conditions we are looking for

  rules:
    - name: Check payload
      condition: event.payload.message == "Create VM"   

  ## Define the action we should take should the condition be met

      action:
        #run_playbook:
        #  name: hello.yml
        run_job_template:
          name: hello world job template
          organization: Default
